version: '2'
services:
    zookeeper:
        image: quay.io/debezium/zookeeper:2.5
        ports:
            - 2181:2181
            - 2888:2888
            - 3888:3888
    kafka:
        image: quay.io/debezium/kafka:2.5
        ports:
            - 9092:9092
        links:
            - zookeeper
        environment:
            - ZOOKEEPER_CONNECT=zookeeper:2181
    mysql:
        image: quay.io/debezium/example-mysql:2.5
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD=debezium
            - MYSQL_USER=mysqluser
            - MYSQL_PASSWORD=mysqlpw
    postgres:
        image: quay.io/debezium/postgres:9.6
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_USER=postgresuser
            - POSTGRES_PASSWORD=postgrespw
            - POSTGRES_DB=inventory
    elastic:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
        ports:
            - "9200:9200"
        environment:
            - http.host=0.0.0.0
            - transport.host=127.0.0.1
            - xpack.security.enabled=false
    connect:
        image: debezium/connect-jdbc-es:2.5
        build:
            context: .
            args:
                DEBEZIUM_VERSION: 2.5
        ports:
            - 8083:8083
            - 5017:5005
        links:
            - kafka
            - mysql
            - postgres
            - elastic
        environment:
            - BOOTSTRAP_SERVERS=kafka:9092
            - GROUP_ID=1
            - CONFIG_STORAGE_TOPIC=my_connect_configs
            - OFFSET_STORAGE_TOPIC=my_connect_offsets
            - STATUS_STORAGE_TOPIC=my_source_connect_statuses
    kafka-ui:
        container_name: kafka_ui
        ports:
            - 8090:8080
        links:
            - kafka:kafka
        environment:
            - KAFKA_CLUSTERS_0_NAME=local
            - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
        image: provectuslabs/kafka-ui:latest
    mongodb:
        image: mongo
        container_name: mongodb
        environment:
            MONGO_INITDB_ROOT_USERNAME: debezium
            MONGO_INITDB_ROOT_PASSWORD: dbz
            # MONGODB_USER: debezium
            # MONGODB_PASSWORD: dbz
        ports:
            - 27017:27017
        restart: always
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: mongo
            ME_CONFIG_MONGODB_ADMINPASSWORD: mongo
            ME_CONFIG_MONGODB_URL: mongodb://debezium:dbz@mongodb:27017/
            ME_CONFIG_BASICAUTH: false
        ports:
            - 8887:8081
        restart: always
